# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-10-09 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categroymodel',
            name='categroy',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexs.CategroyModel', verbose_name='类别上级'),
        ),
    ]
