# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-10-09 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexs', '0002_auto_20201009_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categroy', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='indexs.CategroyModel', verbose_name='视频分类')),
            ],
            options={
                'db_table': 'tb_classificat',
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='视频名字')),
                ('time', models.CharField(max_length=100, null=True, verbose_name='电影播放长度')),
                ('url', models.CharField(max_length=500, null=True, verbose_name='视频地址表')),
                ('imagepath', models.CharField(max_length=2000, null=True, verbose_name='图片地址')),
                ('saveimagepath', models.CharField(max_length=500, null=True, verbose_name='图片保存地址')),
                ('score', models.FloatField(max_length=10, null=True, verbose_name='评分')),
                ('status', models.IntegerField(max_length=10, null=True, verbose_name='状态')),
                ('categroy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexs.CategroyModel', verbose_name='类型')),
            ],
            options={
                'db_table': 'tb_video',
            },
        ),
        migrations.AddField(
            model_name='classificationmodel',
            name='video',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='indexs.VideoModel', verbose_name='视频'),
        ),
    ]
