# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-10-11 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexs', '0003_auto_20201009_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='activate',
            field=models.IntegerField(default=1, verbose_name='观看量'),
        ),
        migrations.AlterField(
            model_name='categroymodel',
            name='categroy',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='indexs.CategroyModel', verbose_name='类别上级'),
        ),
    ]
