# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-10-11 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexs', '0004_auto_20201011_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDelailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='主演')),
                ('refer', models.CharField(max_length=500, null=True)),
                ('categroy', models.CharField(max_length=500, null=True)),
                ('des', models.CharField(max_length=3000, null=True)),
            ],
            options={
                'db_table': 'tb_moviedetailtable',
            },
        ),
        migrations.AddField(
            model_name='videomodel',
            name='secorews',
            field=models.IntegerField(default=1314, verbose_name='评分人数'),
        ),
        migrations.AddField(
            model_name='moviedelailmodel',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexs.VideoModel'),
        ),
    ]
