# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-10-08 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_opt_in',
            field=models.IntegerField(default=0),
        ),
    ]
