# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-10-12 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformerDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('e_name', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(default='', max_length=10)),
                ('bloodtype', models.CharField(max_length=5, null=True)),
                ('height', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('birthay', models.CharField(max_length=50, null=True)),
                ('constellation', models.CharField(max_length=500, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('ResidentialAddress', models.CharField(max_length=100, null=True)),
                ('school', models.CharField(max_length=200, null=True)),
                ('BrokerageAgency', models.CharField(max_length=200, null=True)),
                ('fameyear', models.CharField(max_length=200, null=True)),
                ('hobby', models.CharField(max_length=1000, null=True)),
                ('Occupation', models.CharField(max_length=500, null=True)),
                ('weight', models.CharField(max_length=500, null=True)),
                ('image', models.CharField(max_length=1000, null=True)),
                ('des', models.CharField(max_length=2000, null=True)),
            ],
            options={
                'db_table': 'performerdetailtable',
            },
        ),
    ]
